name: Build Dev APK

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Write local.properties with build hash
        run: |
          echo "BUILD_HASH=pr${{ github.event.pull_request.number }}" > android/local.properties


      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.13.1'

      - name: Install dependencies
        run: yarn install

      - name: Build Dev APK
        run: ./gradlew assembleDevDebug
        working-directory: android

      - name: Upload Dev APK
        uses: actions/upload-artifact@v4
        with:
          name: dev-apk
          path: app/build/outputs/apk/dev/debug/app-dev-debug.apk
