name: Build iOS App (Preview)

on:
  workflow_dispatch:  # Manual trigger
  pull_request:
    branches: [main]

jobs:
  ios-preview-build:
    name: Build iOS App with Clean .env
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Fastlane
        run: sudo gem install fastlane -NV

      - name: Remove Derived Data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Set up Node & Install Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install NPM Packages
        run: npm ci

      - name: Install iOS Pods
        working-directory: ios
        run: pod install

      - name: Build IPA with Clean Env
        working-directory: ios
        run: |
          export ENVFILE=.env.pr_preview
          fastlane run build_app \
            scheme:"YourAppScheme" \
            clean:true \
            export_method:"ad-hoc" \
            output_directory:"./build" \
            output_name:"AppPreview.ipa"

      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS Preview App
          path: ios/build/AppPreview.ipa
