name: iOS Build

on:
  workflow_dispatch:  # You can manually trigger the build from GitHub Actions tab
  push:
    branches:
      - main  # Or your default branch (change if needed)

jobs:
  build-ios:
    runs-on: macos-14  # Use latest stable macOS runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.13.1'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Remove Xcode Derived Data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Clean Xcode build
        run: |
          xcodebuild clean \
            -workspace ios/YourApp.xcworkspace \
            -scheme YourApp \
            -configuration Release

      - name: Build iOS app
        run: |
          xcodebuild \
            -workspace ios/YourApp.xcworkspace \
            -scheme YourApp \
            -configuration Release \
            -sdk iphoneos \
            -allowProvisioningUpdates
